// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4239966d-fcfd-4937-a1f4-3ed8dc094cdc";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHumidityChange();
void onTemperatureChange();
void onAspspeedChange();
void onAsplampChange();
void onOtomatikModChange();

float humidity;
float temperature;
int aspspeed;
bool asplamp;
bool otomatikMod;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humidity, READWRITE, 3 * SECONDS, onHumidityChange);
  ArduinoCloud.addProperty(temperature, READWRITE, 3 * SECONDS, onTemperatureChange);
  ArduinoCloud.addProperty(aspspeed, READWRITE, ON_CHANGE, onAspspeedChange);
  ArduinoCloud.addProperty(asplamp, READWRITE, ON_CHANGE, onAsplampChange);
  ArduinoCloud.addProperty(otomatikMod, READWRITE, ON_CHANGE, onOtomatikModChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
